### ISSUE TITLE
0.7.1 broken on Android Chrome and Webview

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri-exercise-perseus-plugin#111]
Tested on Android 4.4 Chrome via Browserstack

```
[DEBUG: ../kolibri_exercise_perseus_plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue] There was an error loading the assessment item data:  TypeError: Cannot read property 'render' of undefined
    at t.i._renderMath (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:75:31779)
    at t.componentDidMount (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:75:31879)
    at r.notifyAll (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:62:27948)
    at r.close (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:84:21945)
    at r.closeAll (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:37:28423)
    at r.perform (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:37:27867)
    at s (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:63:8212)
    at Object.batchedUpdates (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:84:14897)
    at Object.i [as batchedUpdates] (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:36:10282)
    at Object._renderNewRootComponent (http://127.0.0.1:8000/static/exercise_perseus_render_module/exercise_perseus_render_module-0.6.dev020170927204431-git.js:63:9435)
```

**Comment by christianmemije** [comment]
Fixed in #112
