### ISSUE TITLE
Issue resolving paths

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri-exercise-perseus-plugin#116]
```
    WARNING in .-exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/module.js
    
    /home/christian/repos/kolibri-exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/module.js
      3:31  error  Unable to resolve path to module './views/index'  import/no-unresolved
    
    ✖ 1 problem (1 error, 0 warnings)
    
    
    ERROR in .-exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue
    Module build failed: Error: ENOENT: no such file or directory, open '/home/christian/repos/kolibri/exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue'
        at Error (native)
        at Object.fs.openSync (fs.js:642:18)
        at Object.fs.writeFileSync (fs.js:1356:33)
        at report.results.filter.forEach.result (/home/christian/repos/kolibri/node_modules/eslint/lib/cli-engine.js:449:16)
        at Array.forEach (native)
        at Function.outputFixes (/home/christian/repos/kolibri/node_modules/eslint/lib/cli-engine.js:448:74)
        at printLinterOutput (/home/christian/repos/kolibri/node_modules/eslint-loader/index.js:71:24)
        at Object.module.exports (/home/christian/repos/kolibri/node_modules/eslint-loader/index.js:213:3)

```

1. Cannot resolve the path of index.vue. 
2. The path
`'/home/christian/repos/kolibri/exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue'` is incorrect. It should be `'/home/christian/repos/kolibri-exercise-perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue'`

Using the 0.7 kolibri-exercise-perseus-plugin branch and the develop Kolibri branch.

**Comment by christianmemije** [comment]
Fixed in  https://github.com/learningequality/kolibri/pull/3277
